GET http://localhost:5102/games
### 
GET http://localhost:5102/games/1
### 
GET http://localhost:5102/games/2
### 
GET http://localhost:5102/games/3

### 200 ok /return null
GET http://localhost:5102/games/4

### 404 Not Found 
GET http://localhost:5102/games/4/id

### 400 Bad Request
GET http://localhost:5102/games/id

